name: Build and deploy to itch.io
on: 
  push:
    branches:
      - main

jobs:
  export_game:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
  
      - name: Export game
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          use_preset_export_path: true
          export_debug: false

      - name: Upload web build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_KEY }}
          gameData: ./bin/web/web.zip
          itchUsername: andreiborza
          itchGameId: sentry-jump
          buildChannel: html5

      - name: Upload windows build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_KEY }}
          gameData: ./bin/win/win.zip
          itchUsername: andreiborza
          itchGameId: sentry-jump
          buildChannel: windows

